# Tensor Exchange Dimension

In [2]:
import torch
import numpy as np

In [3]:
tensor_a = torch.randn(2,4,2,2)
tensor_b = torch.randn(2,4,3,3)
print("tensor_a.size()=", tensor_a.size())
print("tensor_b.size()=", tensor_b.size())
print("---------------------------------------------------------------")
print(tensor_a)
print("---------------------------------------------------------------")
print(tensor_b)

tensor_a.size()= torch.Size([2, 4, 2, 2])
tensor_b.size()= torch.Size([2, 4, 3, 3])
---------------------------------------------------------------
tensor([[[[-0.7536,  0.3687],
          [-1.7762, -1.7377]],

         [[ 0.3315, -0.4378],
          [-0.3665, -0.7352]],

         [[-0.3099,  0.0761],
          [ 0.5110,  0.2858]],

         [[ 0.8917, -1.2555],
          [-1.6571,  0.8179]]],


        [[[-0.5506, -0.5262],
          [-0.2250,  1.3002]],

         [[ 1.6878, -2.6623],
          [ 0.1684,  0.3415]],

         [[-0.3902, -1.2010],
          [ 0.7101,  0.8836]],

         [[ 1.1402,  1.0461],
          [-0.1573,  0.1047]]]])
---------------------------------------------------------------
tensor([[[[ 0.1888,  2.6757,  1.2602],
          [-1.8848, -0.6938, -0.1510],
          [ 1.4332,  0.7185, -0.1870]],

         [[ 1.1423,  0.6607,  0.8465],
          [-0.3815,  1.1218,  0.0252],
          [-1.0943, -0.1172, -2.1024]],

         [[ 0.9375, -1.1554,  0.0150],
          [-

In [4]:
tensor_a_T = tensor_a.permute(0,2,3,1).contiguous()
tensor_b_T = tensor_b.permute(0,2,3,1).contiguous()
print("tensor_a_T.size()=", tensor_a_T.size())
print("tensor_b_T.size()=", tensor_b_T.size())

tensor_a_T.size()= torch.Size([2, 2, 2, 4])
tensor_b_T.size()= torch.Size([2, 3, 3, 4])


In [5]:
tensor_cat = torch.cat([tensor_a_T.view(2,-1,4), tensor_b_T.view(2,-1,4)], dim=1)
print("tensor_cat.size()=", tensor_cat.size())

tensor_cat.size()= torch.Size([2, 13, 4])


In [6]:
tensor_l, tensor_r = torch.split(tensor_cat, [2*2, 3*3], dim=1)
tensor_a_ = tensor_l.reshape(2,2,2,4).permute(0,3,1,2).contiguous()

print(tensor_a)
print()
print(tensor_a_)
print()
print("tensor_a == tensor_a_ : ", 0==(tensor_a!=tensor_a_).sum())

tensor([[[[-0.7536,  0.3687],
          [-1.7762, -1.7377]],

         [[ 0.3315, -0.4378],
          [-0.3665, -0.7352]],

         [[-0.3099,  0.0761],
          [ 0.5110,  0.2858]],

         [[ 0.8917, -1.2555],
          [-1.6571,  0.8179]]],


        [[[-0.5506, -0.5262],
          [-0.2250,  1.3002]],

         [[ 1.6878, -2.6623],
          [ 0.1684,  0.3415]],

         [[-0.3902, -1.2010],
          [ 0.7101,  0.8836]],

         [[ 1.1402,  1.0461],
          [-0.1573,  0.1047]]]])

tensor([[[[-0.7536,  0.3687],
          [-1.7762, -1.7377]],

         [[ 0.3315, -0.4378],
          [-0.3665, -0.7352]],

         [[-0.3099,  0.0761],
          [ 0.5110,  0.2858]],

         [[ 0.8917, -1.2555],
          [-1.6571,  0.8179]]],


        [[[-0.5506, -0.5262],
          [-0.2250,  1.3002]],

         [[ 1.6878, -2.6623],
          [ 0.1684,  0.3415]],

         [[-0.3902, -1.2010],
          [ 0.7101,  0.8836]],

         [[ 1.1402,  1.0461],
          [-0.1573,  0.1047]]]])



In [7]:
print("tensor_a[0]=")
print(tensor_a[0])

tensor_a_0 = tensor_l[0].reshape(2,2,4).permute(2,0,1).contiguous()
print("tensor_a_0=")
print(tensor_a_0)

print()
print("tensor_a[0] == tensor_a_0 : ", 0==(tensor_a[0]!=tensor_a_0).sum())

tensor_a[0]=
tensor([[[-0.7536,  0.3687],
         [-1.7762, -1.7377]],

        [[ 0.3315, -0.4378],
         [-0.3665, -0.7352]],

        [[-0.3099,  0.0761],
         [ 0.5110,  0.2858]],

        [[ 0.8917, -1.2555],
         [-1.6571,  0.8179]]])
tensor_a_0=
tensor([[[-0.7536,  0.3687],
         [-1.7762, -1.7377]],

        [[ 0.3315, -0.4378],
         [-0.3665, -0.7352]],

        [[-0.3099,  0.0761],
         [ 0.5110,  0.2858]],

        [[ 0.8917, -1.2555],
         [-1.6571,  0.8179]]])

tensor_a[0] == tensor_a_0 :  tensor(True)
