# Tensor Exchange Dimension

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.randn(2,4,2,2)
tensor_b = torch.randn(2,4,3,3)
print("tensor_a.size()=", tensor_a.size())
print("tensor_b.size()=", tensor_b.size())
print("---------------------------------------------------------------")
print(tensor_a)
print("---------------------------------------------------------------")
print(tensor_b)

tensor_a.size()= torch.Size([2, 4, 2, 2])
tensor_b.size()= torch.Size([2, 4, 3, 3])
---------------------------------------------------------------
tensor([[[[-0.2950, -0.1049],
          [ 0.4943,  0.8125]],

         [[ 1.8520, -1.3790],
          [ 0.4468,  0.5885]],

         [[-0.2927,  1.1160],
          [-1.6372, -0.5932]],

         [[ 0.4793, -0.3600],
          [-0.2236,  1.2922]]],


        [[[-1.4692, -0.4598],
          [-0.2514, -0.9780]],

         [[-1.2009,  0.1763],
          [ 1.6051, -1.8427]],

         [[-0.2851, -0.6409],
          [-0.0876, -0.2794]],

         [[ 0.5338, -1.8694],
          [-1.0536, -1.4762]]]])
---------------------------------------------------------------
tensor([[[[-0.4113,  1.3919, -1.1065],
          [ 0.1296,  0.5952,  1.0343],
          [ 1.2083,  0.4739, -0.0143]],

         [[-0.4079,  1.0941,  0.8205],
          [-1.1087,  1.1520, -0.7836],
          [-2.2417,  1.2064, -0.4478]],

         [[-0.7065,  0.3862,  0.5779],
          [-

In [3]:
tensor_a_T = tensor_a.permute(0,2,3,1).contiguous()
tensor_b_T = tensor_b.permute(0,2,3,1).contiguous()
print("tensor_a_T.size()=", tensor_a_T.size())
print("tensor_b_T.size()=", tensor_b_T.size())

tensor_a_T.size()= torch.Size([2, 2, 2, 4])
tensor_b_T.size()= torch.Size([2, 3, 3, 4])


In [4]:
tensor_cat = torch.cat([tensor_a_T.view(2,-1,4), tensor_b_T.view(2,-1,4)], dim=1)
print("tensor_cat.size()=", tensor_cat.size())

tensor_cat.size()= torch.Size([2, 13, 4])


In [12]:
tensor_l, tensor_r = torch.split(tensor_cat, [2*2, 3*3], dim=1)
tensor_a_ = tensor_l.reshape(2,2,2,4).permute(0,3,1,2).contiguous()

print(tensor_a)
print()
print(tensor_a_)
print()
print("tensor_a == tensor_a_ : ", 0==(tensor_a!=tensor_a_).sum())

tensor([[[[-0.2950, -0.1049],
          [ 0.4943,  0.8125]],

         [[ 1.8520, -1.3790],
          [ 0.4468,  0.5885]],

         [[-0.2927,  1.1160],
          [-1.6372, -0.5932]],

         [[ 0.4793, -0.3600],
          [-0.2236,  1.2922]]],


        [[[-1.4692, -0.4598],
          [-0.2514, -0.9780]],

         [[-1.2009,  0.1763],
          [ 1.6051, -1.8427]],

         [[-0.2851, -0.6409],
          [-0.0876, -0.2794]],

         [[ 0.5338, -1.8694],
          [-1.0536, -1.4762]]]])

tensor([[[[-0.2950, -0.1049],
          [ 0.4943,  0.8125]],

         [[ 1.8520, -1.3790],
          [ 0.4468,  0.5885]],

         [[-0.2927,  1.1160],
          [-1.6372, -0.5932]],

         [[ 0.4793, -0.3600],
          [-0.2236,  1.2922]]],


        [[[-1.4692, -0.4598],
          [-0.2514, -0.9780]],

         [[-1.2009,  0.1763],
          [ 1.6051, -1.8427]],

         [[-0.2851, -0.6409],
          [-0.0876, -0.2794]],

         [[ 0.5338, -1.8694],
          [-1.0536, -1.4762]]]])

